[Settings]
[build]
  command = "npm run build"
  base = "website"
  publish = "website/build"

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/docs/*"
  to = "/:splat"

[[redirects]]
  from = "/zip-stream/*"
  to = "/zipstream:splat"
  status = 301
  
